name: chatgpt
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_chat_ui: ^1.6.6
  flutter_easylogger: ^2.3.3
  flutter_hooks: ^0.18.5+1
  flutter_screenutil: ^5.5.4
  flutter_speed_dial: ^6.2.0
  flutter_spinkit: ^5.1.0
  fpdart: ^0.4.0
  gap: ^2.0.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.2
  icons_plus: ^4.0.0
  lottie: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
